spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pete_comp
    username: peteadmin
    password: somedbpass123
  hikari:
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080