spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pete_comp
    username: peteadmin
    password: somedbpass123
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  transaction:
    default-timeout: 30s
server:
  port: 8080
  ssl:
    key-alias: saving-account-app
    key-store: classpath:saving-account-app.jks
    key-store-type: JKS
    key-password: testing
